name: Assign issue to contributor
on: 
  issue_comment:

jobs:
  assign:
    name: Take an issue
    runs-on: ubuntu-latest
    steps:
    - name: take the issue
      uses: damccorm/take-and-close-action@b37b245
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        take: .take-issue
        close: .close-issue
