name: build_release_candidate

# Workflow added after https://github.com/apache/beam/commit/4183e747becebd18becee5fff547af365910fc9c
# If help is needed debugging issues, you can view the release guide at that commit for guidance on how to do this manually.
# (https://github.com/apache/beam/blob/4183e747becebd18becee5fff547af365910fc9c/website/www/site/content/en/contribute/release-guide.md)
on:
  workflow_dispatch:
    inputs:
      APACHE_PASSWORD:
        description: Your Apache password. Required if you want to stage artifacts into https://dist.apache.org/repos/dist/dev/beam/
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Validate and mask apache id/password
        run: |
          echo "::add-mask::$APACHE_PASSWORD"
        env:
          APACHE_PASSWORD: ${{ github.event.inputs.APACHE_PASSWORD }}
      - run: echo ${{ github.event.inputs.APACHE_PASSWORD }}
      
