name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - name: Recap changes
        id: pr-stats
        uses: damccorm/pull-request-stats@users/damccorm/setOutput
        with:
          token: ${{ secrets.GH_TOKEN }}
          repositories: 'apache/beam'
          period: 90
          charts: 'true'
      - run: echo ${{steps.pr-stats.outputs.results}}
