name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - name: Recap changes
        id: pr-stats
        uses: damccorm/pull-request-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          repositories: 'apache/beam'
          period: 90
          charts: 'true'
      - uses: actions/github-script@master
        with:
          script: |
            let test = String.raw`${{ steps.pr-stats.outputs.results }}`
            console.log(test)
