name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Recap changes
        id: pr-stats
        uses: flowwer-dev/pull-request-stats@126f3be1231eaf2caa433f8c93a4a79150c8a581
        with:
          token: ${{ secrets.GH_TOKEN }}
          repositories: 'apache/beam'
          period: 90
          charts: 'true'
      - uses: actions/github-script@master
        with:
          script: |
            const fs = require('fs')
            let results = String.raw`${{ steps.pr-stats.outputs.resultsMd }}`
            console.log(results)
            fs.writeFileSync('sendPrStats/results.txt', results)
      - run: |
          npm ci
          node sendPrStats.js
        working-directory: 'sendPrStats'
        env:
          ISSUE_REPORT_SENDER_EMAIL_SERVICE: "gmail"
          ISSUE_REPORT_SENDER_EMAIL_ADDRESS: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_ADDRESS }}
          ISSUE_REPORT_SENDER_EMAIL_PASSWORD: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_PASSWORD }}
          ISSUE_REPORT_RECIPIENT_EMAIL_ADDRESS: ${{ secrets.ISSUE_REPORT_RECIPIENT_EMAIL_ADDRESS }}
