name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - name: Recap changes
        id: pr-stats
        uses: damccorm/pull-request-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          repositories: 'apache/beam'
          period: 90
          charts: 'true'
      - uses: actions/github-script@master
        with:
          script: |
            const fs = require('fs')
            let test = String.raw`${{ steps.pr-stats.outputs.results }}`
            console.log(test)
            fs.writeFileSync('results.txt', test)
      - run: |
          npm ci
          node sendPrStats.js
        working-directory: 'sendPrStats'
        env:
          ISSUE_REPORT_SENDER_EMAIL_SERVICE: "gmail"
          ISSUE_REPORT_SENDER_EMAIL_ADDRESS: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_ADDRESS }}
          ISSUE_REPORT_SENDER_EMAIL_PASSWORD: ${{ secrets.ISSUE_REPORT_SENDER_EMAIL_PASSWORD }}
          ISSUE_REPORT_RECIPIENT_EMAIL_ADDRESS: ${{ secrets.ISSUE_REPORT_RECEIVER_EMAIL_ADDRESS }}
