name: Pull Request Stats

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  recap:
    runs-on: ubuntu-latest
    steps:
      - name: Recap changes
        uses: damccorm/pull-request-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          repositories: 'apache/beam'
          period: 90
          charts: 'true'
        env:
          GITHUB_STEP_SUMMARY: 'summary.txt'
      - run: echo $GITHUB_STEP_SUMMARY
      - run: ls /home/runner/work/_temp/_runner_file_commands
