name: temp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issue_comment:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # This should fail the workflow

