name: temp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: if test $(date +%A) == "Thursday"; then echo "IS_FRIDAY=true" >> $GITHUB_ENV; fi

      - name: Run a one-line script
        run: printenv
        env:
          TEST: ${{ env.IS_FRIDAY }}

