name: temp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  issue_comment:

  workflow_dispatch:
  schedule:
  - cron: "* * * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1

